FROM microsoft/aspnetcore-build:2 as publish
WORKDIR /src
COPY / /src/
RUN dotnet publish -c Release -o /publish .

FROM microsoft/aspnetcore:2
COPY --from=publish /publish /app
WORKDIR /app
ENTRYPOINT ["dotnet", "webdevcore.dll"]
